if: tag IS blank

language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

after_success:
  - ./gradlew jacocoTestReport coveralls

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "**/build/libs/*"
  overwrite: true
  prerelease: true
  name: "Unnamed"
  draft: true
  on:
    tags: true