if: tag IS blank

language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

after_success:
  - ./gradlew coveralls

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Yun-Shan"
  - git config --local user.email "yunshan21st@qq.cin"
  - export TRAVIS_TAG=v0.0.1-alpha-build$TRAVIS_BUILD_NUMBER
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "**/build/libs/*"
  overwrite: true
  prerelease: true
  name: "0.0.1-alpha Build $TRAVIS_BUILD_NUMBER"